import 'package:flutter/material.dart';

Map<int, int> iconNames = <int, int>{
  Icons.add.codePoint: 0xe145,
  Icons.camera.codePoint: 0xe3af,
  Icons.arrow_upward.codePoint: 0xe5d8,
  Icons.arrow_circle_up.codePoint: 0xf182,
  Icons.arrow_downward.codePoint: 0xe5db,
  Icons.arrow_circle_down.codePoint: 0xf181,
  Icons.swap_vert.codePoint: 0xe8d5,
  Icons.swap_vert_circle.codePoint: 0xe8d6,
  Icons.swap_horiz.codePoint: 0xe8d4,
  Icons.swap_horizontal_circle.codePoint: 0xe933,
  Icons.cancel.codePoint: 0xe5c9,
  Icons.dangerous.codePoint: 0xe99a,
  Icons.check.codePoint: 0xe5ca,
  Icons.man.codePoint: 0xe4eb,
  Icons.mode_standby.codePoint: 0xf037,
  Icons.square.codePoint: 0xeb36,
  Icons.circle.codePoint: 0xef4a,
  Icons.hexagon.codePoint: 0xeb39,
  Icons.pentagon.codePoint: 0xeb50,
  Icons.minimize.codePoint: 0xe931,
  Icons.maximize.codePoint: 0xe930,
  Icons.star.codePoint: 0xe838,
  Icons.star_border.codePoint: 0xe83a,
  Icons.favorite.codePoint: 0xe87d,
  Icons.favorite_border.codePoint: 0xe87e,
  Icons.group.codePoint: 0xe7ef,
};
